// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReverseEnginereeingEF.Data;

#nullable disable

namespace ReverseEnginereeingEF.Migrations
{
    [DbContext(typeof(NADLANContext))]
    partial class NADLANContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("ReverseEnginereeingEF.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompanyID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("Company Name");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("Website")
                        .HasMaxLength(124)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Alpha-2 Code");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Alpha-3 Code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numeric")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("CountryId");

                    b.HasIndex(new[] { "CountryName" }, "UQ__Countrie__E056F201DD0CDF79")
                        .IsUnique();

                    b.HasIndex(new[] { "Numeric" }, "UQ__Countrie__FD07398E83A4904D")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.ExperienceLevel", b =>
                {
                    b.Property<string>("Level")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("Level")
                        .HasName("PK__Experien__AAF899630983E740");

                    b.ToTable("Experience Levels");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("HouseID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BuiltAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Built At");

                    b.Property<bool>("ForSale")
                        .HasColumnType("INTEGER")
                        .HasColumnName("For Sale");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NeighborhoodID");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OwnerID");

                    b.Property<int>("Rooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeM2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Size (M^2)");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeID")
                        .IsFixedLength();

                    b.Property<decimal>("WantedPrice")
                        .HasColumnType("money")
                        .HasColumnName("Wanted Price");

                    b.HasKey("HouseId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.HouseType", b =>
                {
                    b.Property<string>("TypeId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeID")
                        .IsFixedLength();

                    b.HasKey("TypeId")
                        .HasName("PK__House ty__516F0395EF75E4DB");

                    b.ToTable("House types");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Neighborhood", b =>
                {
                    b.Property<int>("NeighborhoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("NeighborhoodID");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("NeighborhoodId");

                    b.HasIndex("CityId");

                    b.ToTable("Neighborhoods");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PersonID");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompanyID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("First Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("Last Name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone Number");

                    b.HasKey("PersonId");

                    b.HasIndex("CompanyId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__People__79578B9366CF0684")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SaleID");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BuyerID");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("money")
                        .HasColumnName("Final Price");

                    b.Property<int>("HouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HouseID");

                    b.Property<float>("Income")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValueSql("((0.05))");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Publish Date");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Sale date");

                    b.Property<int>("SalesManId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SalesManID");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SellerID");

                    b.HasKey("SaleId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("HouseId");

                    b.HasIndex("SalesManId");

                    b.HasIndex("SellerId");

                    b.HasIndex(new[] { "SaleId" }, "UQ__Sales__1EE3C41E0DBBEAF7")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.SalesMan", b =>
                {
                    b.Property<int>("SalesManId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SalesManID");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Birth Date");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompanyID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("First Name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Hire Date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Last Name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone Number");

                    b.HasKey("SalesManId");

                    b.HasIndex("CompanyId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__SalesMen__79578B93B9FBA71A")
                        .IsUnique();

                    b.ToTable("SalesMen");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Specialization", b =>
                {
                    b.Property<int>("SalesManId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SalesManID");

                    b.Property<string>("TypeId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeID")
                        .IsFixedLength();

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("SalesManId", "TypeId")
                        .HasName("PK__Speciali__6F0E227E4CD88706");

                    b.HasIndex("Level");

                    b.HasIndex("TypeId");

                    b.ToTable("Specialization");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.VAvailableHouse", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("BuiltAt")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("Built At");

                    b.Property<int>("ForSaleHouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("For sale HouseID");

                    b.Property<int?>("HouseOwnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HouseOwnerID");

                    b.Property<string>("Neighbor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int>("NeighborId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NeighborID");

                    b.Property<int>("Rooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SameCityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SameCityID");

                    b.Property<int>("SizeM2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Size (M^2)");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeID")
                        .IsFixedLength();

                    b.Property<decimal>("WantedPrice")
                        .HasColumnType("money")
                        .HasColumnName("Wanted Price");

                    b.ToView("V_AVAILABLE_HOUSES");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.VCustomers2yearsExpiry", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(61)
                        .HasColumnType("TEXT")
                        .HasColumnName("Full Name");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PersonID");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone Number");

                    b.Property<string>("SaleDate")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("Sale Date");

                    b.ToView("V_CUSTOMERS_2YEARS_EXPIRY");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.VExcellentWorker", b =>
                {
                    b.Property<int>("SalesManId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SalesManID");

                    b.Property<float?>("TotalIncome")
                        .HasColumnType("REAL")
                        .HasColumnName("Total Income");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.ToView("V_EXCELLENT_WORKER");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.VNeighborhoodTotalPrice", b =>
                {
                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<decimal?>("TotalWanted")
                        .HasColumnType("money")
                        .HasColumnName("Total Wanted");

                    b.ToView("V_Neighborhood_TOTAL_Price");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.City", b =>
                {
                    b.HasOne("ReverseEnginereeingEF.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__CountryI__2B3F6F97");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.House", b =>
                {
                    b.HasOne("ReverseEnginereeingEF.Models.Neighborhood", "Neighborhood")
                        .WithMany("Houses")
                        .HasForeignKey("NeighborhoodId")
                        .IsRequired()
                        .HasConstraintName("FK__Houses__Neighbor__4CA06362");

                    b.HasOne("ReverseEnginereeingEF.Models.Person", "Owner")
                        .WithMany("Houses")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK__Houses__OwnerID__4AB81AF0");

                    b.HasOne("ReverseEnginereeingEF.Models.HouseType", "Type")
                        .WithMany("Houses")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Houses__TypeID__4BAC3F29");

                    b.Navigation("Neighborhood");

                    b.Navigation("Owner");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Neighborhood", b =>
                {
                    b.HasOne("ReverseEnginereeingEF.Models.City", "City")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Neighborh__CityI__2E1BDC42");

                    b.Navigation("City");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Person", b =>
                {
                    b.HasOne("ReverseEnginereeingEF.Models.Company", "Company")
                        .WithMany("People")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK__People__CompanyI__35BCFE0A");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Sale", b =>
                {
                    b.HasOne("ReverseEnginereeingEF.Models.Person", "Buyer")
                        .WithMany("SaleBuyers")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK__Sales__BuyerID__5165187F");

                    b.HasOne("ReverseEnginereeingEF.Models.House", "House")
                        .WithMany("Sales")
                        .HasForeignKey("HouseId")
                        .IsRequired()
                        .HasConstraintName("FK__Sales__HouseID__5070F446");

                    b.HasOne("ReverseEnginereeingEF.Models.SalesMan", "SalesMan")
                        .WithMany("Sales")
                        .HasForeignKey("SalesManId")
                        .IsRequired()
                        .HasConstraintName("FK__Sales__SalesManI__5441852A");

                    b.HasOne("ReverseEnginereeingEF.Models.Person", "Seller")
                        .WithMany("SaleSellers")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK__Sales__SellerID__52593CB8");

                    b.Navigation("Buyer");

                    b.Navigation("House");

                    b.Navigation("SalesMan");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.SalesMan", b =>
                {
                    b.HasOne("ReverseEnginereeingEF.Models.Company", "Company")
                        .WithMany("SalesMen")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK__SalesMen__Compan__3A81B327");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Specialization", b =>
                {
                    b.HasOne("ReverseEnginereeingEF.Models.ExperienceLevel", "LevelNavigation")
                        .WithMany("Specializations")
                        .HasForeignKey("Level")
                        .IsRequired()
                        .HasConstraintName("FK__Specializ__Level__440B1D61");

                    b.HasOne("ReverseEnginereeingEF.Models.SalesMan", "SalesMan")
                        .WithMany("Specializations")
                        .HasForeignKey("SalesManId")
                        .IsRequired()
                        .HasConstraintName("FK__Specializ__Sales__4222D4EF");

                    b.HasOne("ReverseEnginereeingEF.Models.HouseType", "Type")
                        .WithMany("Specializations")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Specializ__TypeI__4316F928");

                    b.Navigation("LevelNavigation");

                    b.Navigation("SalesMan");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.City", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Company", b =>
                {
                    b.Navigation("People");

                    b.Navigation("SalesMen");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.ExperienceLevel", b =>
                {
                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.House", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.HouseType", b =>
                {
                    b.Navigation("Houses");

                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Neighborhood", b =>
                {
                    b.Navigation("Houses");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.Person", b =>
                {
                    b.Navigation("Houses");

                    b.Navigation("SaleBuyers");

                    b.Navigation("SaleSellers");
                });

            modelBuilder.Entity("ReverseEnginereeingEF.Models.SalesMan", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Specializations");
                });
#pragma warning restore 612, 618
        }
    }
}
